### ISSUE TITLE
Child Table / List handling - Key Field

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#13]
This "Spec" addresses an issue that arises, right now, when a specific record is chosen from a LIST.

(the solution/spec is extremely simple, but describing how it looks when implemented takes longer)

1. In ANY "List"  (usually a child-table, but not always ... any table can be displayed as a list!), the user usually has the option to select a record from the list - that will presumably be edited for more details.

2. Thus - selecting a record from a list - needs to specify several pieces of information to the GPC:
a. which record was chosen  (table, sufficient ID info)
b. what action is to be taken by the GPC when this record is selected
   - this usually means processing a new DD record

3. After selecting the record and 'processing' it (in step 2) the GPC needs to know where and how to return to the prior screen/state.

*Solution/Approach*

1. In the DD we already have parent_key (field) specified, and

**Comment by yasirkhan177** [comment]
specs are not complete.. for processing child list or displaying list .. second keyfield required .. whether it can be another field in DD or it can be parse using the existing dd->parent_key = keyfield1, keyfield1

**Comment by cjcornell** [comment]
Tell me exactly what is missing to make this feature work ... because I am not quite understanding. 
As I am going to be saying a lot now... 
it is better if you just show me what you have in mind .. it will save us both HOURS of work,

**Comment by yasirkhan177** [comment]
i discussed this with you online as well ... in displaying child-list and list( when its a child ) .. we need to keyfields ... one keyfield which will be the primary-key of child table and second keyfield which will be the parent-key of parent table ... there can be two simple solution .. 

1) if we add another field in dd (which is not good)

2) if we parse it ..using same dd->parent_key .. ( key1 = parent-key , key2 = child-key )

**Comment by yasirkhan177** [comment]
for example .... in table >> "project_child" .. GPC need to know two key field values to update the the record of specific project .. which is   child-table-primary-key = id 

and ... parent-table-primary-key= pid 

i hope now you got what i meant ...

**Comment by yasirkhan177** [comment]
needed 5 mins discussion online... and this problem will be solved

**Comment by yasirkhan177** [comment]
i explained it already ... we need two primary key for editing the child table. i can fix it by mentioning two keys .. but i want to know if you have some thing extra in your mind for it or i fix it ?

**Comment by cjcornell** [comment]
READ THIS CAREFULLY! 

It seems as if this is related to 2-3 other issues regarding key fields (or filters).
We need to resolve this!  (in this milestone)

There are several easy approaches (for instance adding new DD fields), but we need to choose one that is also efficient and scalable.
TWO things to consider:
1. we should be (but are probably not), saving the CURRENT user_id to a global variable  (session var), and if a project is chosen then storing the current chosen project too.  This makes a lot of sense
2. in the DD - parent/child really is handled like a filter, FYI, in addition to any list_filter (if DD is a list)

Perhaps this will help us design a more effective way of solving those list / child problems 
ie - if any child-file is chosen, via DD, then perhaps we can already assume
1. that parent_key has been stored in memory (see above)  and this is what we will use to "bind" the DD child record (I am only calling it a "child" table for convenience)
2. if there is no parent_key the the DD record does not use parent_key (and the global var) to filter ... but the DD may use other criteria.

The above might not be 100% specific but I think it is close to resolving the 2 major "issues' we have with lists, and selections based on lists)

Does this make sense?

**Comment by cjcornell** [comment]
Closing this for now - but more testing is needed
