### ISSUE TITLE
Navigation - Display_pages

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#16]
Check out
Home -> myaccount
then go to myprojects  (from the myaccount navigation dropdown)

the problem:
while GPC navigates correctly to the myprojects display_page 
the navigation menu does not operate correctly

**Comment by yasirkhan177** [comment]
when tab ( tab inside myprojects ) are empty then dropdown didn't work. if you fill it with any data ,it will work.. i will still check further
