### ISSUE TITLE
List - Single Line List

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#19]
- Single Line Lists do not appear to be working. (? *listview )
  - See MyProjects tab
- also there is still a "manage scripts button for the records in the list  ... 
  - for lists (single or multiple) ideally we click anywhere on the record to select it

**Comment by yasirkhan177** [comment]
solved

**Comment by cjcornell** [comment]
OK - but don't close github issues.  I verify then and then I close them,  Thanks

**Comment by yasirkhan177** [comment]
i was just checking .. i don't close any issue normally .. wont be happen in future. Thanks

**Comment by cjcornell** [comment]
a. in multiline and single line lists - the user could click anywhere on the line to "select" and edit (without needing to click on the "edit"  (and elimate the "edit" link"
b. please let me know if "a" is a problem - because I want to eliminate the edit "button" link

**Comment by yasirkhan177** [comment]
http://genericveryold.cjcornell.com/projects.php <<< on this page ,if user click on anywhere on the it takes user to different page .. and edit button take user to different page. if it's not the case in current generic .. then (a) is not a problem. i will eliminate the edit button link

**Comment by cjcornell** [comment]
so you will change this so that single and multiline lists can be "edited" (list_select) by clicking anywhere on that line?

**Comment by yasirkhan177** [comment]
i checked that.. i will give you details in a while

**Comment by yasirkhan177** [comment]
Right now i did .. but it's not the way you want. Because it didn't work if you click anywhere on line.. you need to click on the text. Before doing this, just want to inform you that this will run the loop two time .. so it can slow down the system if list is long but pagination will solve this issue as well. but it's bit time taking . Right now working on zapit , will do it later today.

**Comment by cjcornell** [comment]
1. I understand that the user will have to click on text.
2. I am a little concerned about the latency (slowness) - but even more so about the inefficiency.... SO
if you have not coded anything yet.
- Let's just arrange this so there is an "edit" icon (icon only) on the left of the line  (exactly like we do it for zapit2me admin)
- and make sure that we are making good use of css/class style for this button (as well as everything else on the line) - so we can change it later.
I am OK with this solution because, of the css is done right, we have a lot more flexibility for later

**Comment by yasirkhan177** [comment]
ok
