### ISSUE TITLE
Cannot get List->Edit to work

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#24]
I created a DD  record (id=111) -  almost IDENTICAL to "scripts" (id=103)  except I want to display and edit project records..   and I tried every combination of list terms ... ended up leaving it blank.

thus I could not get lists working for projects at all

**Comment by yasirkhan177** [comment]
just take care of one thing.. there should not be table_alias duplication on the same page for tabs.. i mean .. on one page two tabs can't have same table_alias value

**Comment by yasirkhan177** [comment]
scripts >>>> dict_id=103 ... its a child list .. right now to make child list work for any table we need two primary key .. one key for parent table and second key for child table. edit is not working because it don't have second key.

**Comment by yasirkhan177** [comment]
enhancement needed to make it work

**Comment by cjcornell** [comment]
This seems to be related to #13
