### ISSUE TITLE
List Styles

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#25]
As per our slack chat - 
a new field was required:  list_style .... 
this was to be used in all lists  - very much like the way the nav table uses item_style.

if list_style=blank, then any list (especially boxes/cards) uses the default css class for the list type.  but if list_style not blank, then the list uses the css class specified in list_style.

**Comment by yasirkhan177** [comment]
yeh now i remember that you have told me this .. i forgot it because it wasn't written in the specs.. no problem .. it will be dealt

**Comment by yasirkhan177** [comment]
i will do it in the last .. when other bugs are removed

**Comment by cjcornell** [comment]
OK - still pending

**Comment by yasirkhan177** [comment]
added field (list_style) in table DD .. also added class in application/style.css for testing purpose class name = list-style

**Comment by cjcornell** [comment]
OK - I will test when the other issues are resolved
