### ISSUE TITLE
Profile/Update Button

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#26]
Update button should just say "Update" ... not Update Profile.

**Comment by yasirkhan177** [comment]
ok done

**Comment by cjcornell** [comment]
re-opening so I can test and comment

**Comment by cjcornell** [comment]
Not sure what happened here ... but there used to be a CANCEL button next to the Update button.  We always need a cancel button next to the update button on these pages

**Comment by yasirkhan177** [comment]
fixed
