### ISSUE TITLE
Details Tab in myaccount

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#27]
Why is no data displaying?  Check out the DD record for this  (id == 66)

**Comment by yasirkhan177** [comment]
because there is no record  in FD for fd->table_alias='users'

**Comment by cjcornell** [comment]
It would save hours of time - HOURS -  Yasir, if you would just modify the DD and show me,

**Comment by yasirkhan177** [comment]
ok in future i will.. i don't normally make changes (to database) and it's only because i wont do things without your permission .

**Comment by yasirkhan177** [comment]
it wasn't about modifying the DD ... i guess you didn't pay attention to my above comment. i said there is no record in FD for table_alias='users' ..  you asked me the reason why it's not displaying and i gave you the reason.

**Comment by cjcornell** [comment]
yes, there is a table_alias=users in FD    (field_def_id=334) ... i entered it deliberately to display one field for editing under the "Details" tab....
so again, this remains an issue)

**Comment by yasirkhan177** [comment]
one field is displaying and updating is working. why its an issue?

**Comment by cjcornell** [comment]
When I opened the issue - this was not working.  It is working now - so something else you fixed must have fixed this too.

**Comment by yasirkhan177** [comment]
no problem.
