### ISSUE TITLE
list filter

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#29]
Check out DD record 111  (Test - My Projects) List.
This list aways seems to display 1  record.
but since the list_filter is uid=17, this list should display 5 records.
so this is unexpected, at least, and probably a bug of some kind.   Unless there is a good explanation

**Comment by yasirkhan177** [comment]
its dd->table_type = child for dict_id=111 ... and list_filter doesn't apply on child list ..

**Comment by cjcornell** [comment]
This absolutely needs to work!  If there was anything in the spec, and in the comparison with genericveryold - it is this very scenario:
User ->
     List all My projects ->  (select)
               Edit that one project
     (and navigate back, if they want)

AND
DIsplay "my projects"  is not exactly a child relationship (technically it is not a parent-child table relationship) - it is definitely more of a filter relationship

It is really important to get this working, so let me know what is missing or incorrect or what else is needed.

**Comment by cjcornell** [comment]
>> its dd->table_type = child for dict_id=111 ... and list_filter doesn't apply on child list 

re-read my response.
this needs to work   and  list_filter absolute must "apply" for a child-list ...  (sorry - you don't get to change the requirements here)
