### ISSUE TITLE
DD Generation - Do this Second

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#3]
specifying that this task be done SECOND
(because I need more time to establish the DD template data)

The utility should
1. prompt the user to create a new DD or use the existing.
a. if new - then the old data_dictionary is deleted)
and a new data_dictionary is created based on datadictionary_template table
b. if existing, then
during the create process, the utility should overwrite existing DD records that match the key
table_alias + display_page, otherwise, append new record, as usual.

Operation.
For every record in datadictionary_template  (DDT)
the DD Generator will 
1. copy/append that record into the DD - see above
2. update the values in the DD record with specific defaults and special cases

special note ....very important
A Special NEW field will be added to the DD Structure: fields_used
(see issue #2  )

B. we will have a special new file DEFINES  for the application.
these Constants will replace values in DD, when they are created from the DDT
eg
Values Defined
USER="member"
PROJECT="script"
CHILD="command"
TRANSACTION="transaction"
PROFILE="profile"

so when 
a record is being copied from DDT to DD
the utility will replace
Any instance of 
USER
with 
member
if it occurs in the DDT fields:  
database_table_name, 
table_alias
table_type
tab_name
parent_key, 
parent_table
list_filter
list_sort
(the value is only changed in the DD record)

RIGHT NOW - there are no other defaults or special cases needed.

**Comment by yasirkhan177** [comment]
i didn't get this completely .. we need to talk on this before i start work on it.
