### ISSUE TITLE
Nav Bug - under New Tab

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#31]
Strange.  
Navigate to the page myaccount 
there are 4 tabs
- Profile
- Details
- My Transaction
- My Comments

(all these should be the same display_page)
the top navigation under "TestUser" 
is
- myprojects
- logout

but when you click on the last 2 tabs (transactions  or comment)
the navgation dropdown does not work (or is empty)
this is odd, because it should not change at all!

**Comment by yasirkhan177** [comment]
yes i told you that when you click on tab( and its empty) then dropdown didn't work .. its strange and i tried to debug as well but didn't find anything but there must be some thing. i will recheck .

**Comment by cjcornell** [comment]
Ah - that's why did not understand you the first time. For GPC the term "dropdown" refers to a formatted field in on a page of fields.  In this case, you should have said "when a tab is clicked-on, and the page has no fields, then the Navigation menu (dropdown) has a bug"...

OK - but we still have to keep this open as a bug, to be solved.

**Comment by yasirkhan177** [comment]
ok

**Comment by yasirkhan177** [comment]
it will work how long DD values are accurate.
