### ISSUE TITLE
List - Different Views 

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#33]
See "My Projects"  (DD dict_id=112)

Single Line List (choice/option)
why doesn't this look like  "Test - My Projects"  (DD dict_id=111) ?? - which is also a single line list?

They should look very very similar.

**Comment by yasirkhan177** [comment]
default value must be there for list_view ... or let me know to give default value if dd->list_view is NULL

**Comment by cjcornell** [comment]
if dd->list_view=Null then  the record is not a list!

but this does not explain this bug, originally.  but I will close it for now
