### ISSUE TITLE
List Sort - Widget

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#34]
The dropdown sort mechanism ...
See "My Projects"  (DD dict_id=112)

When viewing on the myprojects Display Page ...
and you click on another tab and return to My Projects  tab (1) ... 
the list-sort dropdown no longer works

**Comment by yasirkhan177** [comment]
i take blame for this bug but its really unexpected behavior ..otherwise i would catch that bug and fix it
