### ISSUE TITLE
List Sort (clarification/improvement)

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#35]
In the List Sort UI/Widget
(if indeed using such a widget is the efficient solution)

1. there should not be a "sort" button.  list should sort as soon as the option is chosen from the dropdown list.

2. to make this more flexible.  the first time a selection is chosen, the sort is done in the normal sort order. if the same sort-type is selected again - then the sort order reverses (or rather "toggles" the sort order)

**Comment by yasirkhan177** [comment]
tried to do it without refreshing the page .. but this whole page is generated via data .. too much dependency .. which causing issues ..

**Comment by cjcornell** [comment]
***>> the way it works now I am OK with !!
