### ISSUE TITLE
List - Box Style - 2 select areas

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#38]
- enhancing box style  (two different select-areas).

**Comment by cjcornell** [comment]
This is consistent with the new specs for the list improvements  milestone, just moving this under that milestone

**Comment by yasirkhan177** [comment]
in genericveryold .. when click on image ,,it prompt you to project detail page ... so now in current GPC link will be data driven? or it will prompt to detail page...

**Comment by cjcornell** [comment]
well I was a little more general in my descriptions here.  For any "box" list I just wanted to be able to specify 2 different select-areas (with 2 different actions).
In genericveryold - if you go to "my projects" then you will see that
- if you click on the image, then you go to the "project profile' page
- if you click on 'manage project' you go to the manage project page

I would like a way to be able to do this in the current GP, specifying this, generally using DD

**Comment by yasirkhan177** [comment]
2 areas are there right now .. but i just want to make sure ,how you want 2nd area .. i mean by clicking image in box(card) list . we can use 2nd parameter in dd->list_select as 2nd action .. but there you want some other functionality, like functions etc.

**Comment by cjcornell** [comment]
The two areas might be there  but I cannot really see it
(go to http://generic.cjcornell.com/system/profile.php?display=myprojects&tab=projects&tabNum=7   click box view)

again - I am still puzzled how this deviated so much from genericveryold - which was the reference point for the spec.

And - the point of my mentioning it again here - is that this is another example of a list-record that has more that one possible "selection" type and "action" type - just like you are doing with checklists.

**Comment by yasirkhan177** [comment]
i didn't give any link on image yet...box view will be like genericveryold.

**Comment by cjcornell** [comment]
ok great

**Comment by yasirkhan177** [comment]
i will use 2nd parameter in list_select for an action after clicking on image. it will interpret like the way first parameter of list_select .

**Comment by cjcornell** [comment]
OK - but I was implying this:
- since it looks like you are adding a new field in the DD for the multiple options for checklists, then it might make sense to see how you can use this field to specify the extra options for the box lists.
(maybe).... but it seems to make some sense.
