### ISSUE TITLE
Bug - Manage Proj Tab Fields

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#41]
Look at "Manage Project" tab  (DD_id = 102)
it has table_alias="projects"
but only displays 3 fields (there are more in FD that should display)

**Comment by yasirkhan177** [comment]
because  if you check fd table for table_alias='projects' ... visibility= 0 for rest of fields except 3 fields.

**Comment by cjcornell** [comment]
Thank you.  I wish there was a better way to check for these issues.
