### ISSUE TITLE
formatting of Checkbox 

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#45]
On screen formatting of checkbox is not consistent with the page formatting (see Myaccount or Manage Project)

checkbox label placement should be consistent with other labels ...  

(note format_length can be used to determine the formatting width allowed for the label+box

**Comment by cjcornell** [comment]
solution?

**Comment by yasirkhan177** [comment]
solution will be of course CSS .. and if you add enhancement of using height as well ( which will be used in fd->format_length) in near milestone (upcoming).. then this layout consistency will be dealt properly . but for now i will fix it and will report you

**Comment by yasirkhan177** [comment]
kindly check it now ..

**Comment by cjcornell** [comment]
look at   (http://generic.cjcornell.com/GP-BugReport-Jun-18-01.jpg)

**Comment by yasirkhan177** [comment]
i dealt it, when i said check it now .. did you check now?

**Comment by cjcornell** [comment]
OK works now.
Thanks
