### ISSUE TITLE
List - Truncate fields

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#47]
in ALL list styles - 
fields need to truncate the text (or other contents) in order to maintain formatting ....
note - look at the list for Tab:  Test - My Projects  and how the description field completely messes the formatting.  
list manager must truncate or uniformly format all fields.

**Comment by yasirkhan177** [comment]
that is exceptional .. text-image has been used because of which it is displaying like that .. and in rest of lists .. description ( use editor) ,so it format the way you format it in that EDITOR.  Truncating can be an option ..

**Comment by cjcornell** [comment]
No sir.  This is NOT exceptional.  Actually very long fields (even regular text fields) are common - but need to be truncated in lists.  
What you are suggesting is that the USER truncate their CONTENT because the coding cannot truncate???

**Comment by yasirkhan177** [comment]
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

**Comment by yasirkhan177** [comment]
coding can mostly do anything .. i meant some thing else.. anyways you check now .. also will fix select (editable=false) << one more bug i don't remember the name .. will report in few mins

**Comment by cjcornell** [comment]
This issue is about truncating fields in lists (so the list can maintain their formatting integrity).  Is this done?

As for other issues - do you know how to use github to click on the label to filter "bugs" ?  I don't want to discuss multiple issues within a single comment (unless they are related)

Also - if you need to refer to another issue within a comment thread .. type #  and github will list the other issues for you to reference

**Comment by cjcornell** [comment]
I have tested several times.  
shall I send another screen shot?
are you actually testing using the data on the server and using Test - My Projects
it should be very very very very very obvious that this is not working correctly yet.

**Comment by yasirkhan177** [comment]
i am not actually getting your real point .. by truncating fields in lists ... that's why i am not sure if it's done according to you . do you mean i should not display string further more ,if it reach to certain limit?

**Comment by cjcornell** [comment]
the description field ...
specifically look at the desctription field
and how it displays in the list for Test My Projects tab

expecially the very  first line  (a long descriptuion field that happens to have an embeded image
it does not matter what is in this field .. the list widget should truncate it so that the field display is consistent with all the other records

**Comment by cjcornell** [comment]
bump - this is still a problem

**Comment by yasirkhan177** [comment]
worked on misl tasks .. i didn't fix this ,i'm not yet clear .. by truncate you mean if for example description field has long text data .. it should truncate the data and only display certain characters?

**Comment by cjcornell** [comment]
I am getting rather frustrated with you on this task, Yasir ...
HOW are you not seeing how BADLY the lists are formatting?  READ the prior comments where I clarified and gave examples - Twice.  I even sent a screen shot!
