### ISSUE TITLE
 INVESTIGATE  "Uploadcare"

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#48]
+ We use uploadcare as the method for allowing and manage image uploading  (and editng/cropping etc).
+ uploadcare is partially (90%) implemented throughout the generic platform  (that we are using).
+ you can test uploadcare by clicking on "update" by any "profile" image OR (even better) by going to any tab/page that has rich-text (CKEDIT) and click the "image" icon.

+ the advantages uploadcare:
   - ease of coding
   - works with almost any browser without needing flash or other plugins
   - allows for previewing, editing, cropping, resizing of the photo BEFORE replacing the current one.
   - allows for uploading from various sources - local, web, URL ...  
   - ease of storage

+ The problem: Uploadcare is a "service" that we use via API.  It has limitations - such as file storage limits, or bandwidth - and then a paid tier.
+ we need to find out the limitations, and .. investigate alternatives (ie. libraries or addins)

+ We use uploadcare as the method for allowing and manage image uploading  (and editng/cropping etc).
+ uploadcare is partially (90%) implemented throughout the generic platform  (that we are using).
+ you can test uploadcare by clicking on "update" by any "profile" image OR (even better) by going to any tab/page that has rich-text (CKEDIT) and click the "image" icon.

+ the advantages uploadcare:
   - ease of coding
   - works with almost any browser without needing flash or other plugins
   - allows for previewing, editing, cropping, resizing of the photo BEFORE replacing the current one.
   - allows for uploading from various sources - local, web, URL ...  
   - ease of storage

+ The problem: Uploadcare is a "service" that we use via API.  It has limitations - such as file storage limits, or bandwidth - and then a paid tier.
+ we need to find out the limitations, and .. investigate alternatives (ie. libraries or addins)

Note:
https://uploadcare.com/accounts/
login = cj@cjcornell.com
pasaword= genericplatform
our public key:  4c3637988f9b93d343e8
our secret key: 16c9566ab1cf36425cfMagicm0702*

**Comment by yasirkhan177** [comment]
if you want to have a uploader with editing and croping option .. than its available for free but uploadcare has many options and its very easy to use. but yes it has different packages. With upload care you can upload images from many social networking websites and this option will not be available in free libraries

**Comment by cjcornell** [comment]
My goodness Yasir ...  I know what uploadcare does. We already use it.  I wrote extensively (above on the advantages and disadvantages).

The task here is to 
-  find out the limitations, and .. investigate alternatives (ie. libraries or addins)
- OK - if there are not any Free libraries - are there ANY libraries/code available where we can perform the same functionality on our own server?
- i asked for you to find out alternatives.  This is the task.

**Comment by yasirkhan177** [comment]
i already gave you answer in my previous comment .. but i was not clear in stating it . 

if you only want to have a uploader with editing and croping option then there are free libraries available. But if you want to upload images from different sources like you have in uploadcare then it's not available as for as my survey. i will again search today and will let you know if i find any.

**Comment by cjcornell** [comment]
OK - we'll use uploadcare for now. but I still want you to log in to our uploadcare account, and also look at how we are implementing it within GPC

**Comment by yasirkhan177** [comment]
files are use to upload in /user_uploads << (directory) .. we don't need any backup on uploadcare . we can delete files from there to utilize storage space. Currently it says you can use 250 mb storage space, but i didn't able to see any package which provide 250 mb space? 

.....................................................

don't have any problem of its implementation in GPC. i check it.

**Comment by cjcornell** [comment]
OK I iwll close this for now
