### ISSUE TITLE
Improve Login Page

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#49]
Login Page - make work better with FD (and data-driven scheme)
+ We want the login page to work more consistent to all the other pages - in fact, eventually we want to eliminate the need for a special login page - but not yet.
+ This will require a couple of enhancements to interpreting FD->format_type  and maybe to DD->display_page, more specifically 
  - making sure GP recognizes loginID (or email address) and password 
  - making sure some internal fields are recognized (such as password reset)
  - handles new user registration
  - displays/handles reset-password
+ allowing other info to be displayed on the login page (ie other formatted text/instructions)

**Comment by yasirkhan177** [comment]
making sure GP recognizes loginID (or email address) and password << what do you mean by this? GPC recognize them by fd->format_type already?

making sure some internal fields are recognized (such as password reset) <<< it will be kinda hard coded?

handles new user registration  << will page specific means signup page but will be data driven ( just confirming)

**Comment by cjcornell** [comment]
- making sure GP recognizes loginID (or email address) and password << what do you mean by this? GPC recognize them by fd->format_type already?
   - Yes- GPC (for a special login page) needs to recognize these fields by the format_type

- making sure some internal fields are recognized (such as password reset) <<< it will be kinda hard coded? i mean i will use separate function for it .. just confirming .. and informing
   - I understand.  as long as the field for password reset (and other fields needed for this) are identified by the format_type.  but I understand this may be easier to have hard coded.

- handles new user registration << will page specific means signup page but will be data driven ( just confirming)
   - yes ...  but I think Issue #51  will help ... in other words - we will make use of special display_pages for login and registration (and reset)

The important parts of this tasks are
1. to make login, registration, reset ...  a little more data driven
2. to make the display_pages for them, more data-driven and consistent with the existing page-formatting engine - particularly so we can display other info on these pages and define navigation etc.

**Comment by yasirkhan177** [comment]
here we have major conflict . i waited for you but  deadline was on my head. so i started to finish this milestone. by my analysis ,i came to conclusion that signup ,login ( previously data driven ) and password reset should be static ( not data driven like other pages ) . so i made them separately but other info can be displayed on these pages or it can be define through navigation.

**Comment by cjcornell** [comment]
OK - yes the delays were mine....
so this is not a "major" problem.
let me know when I can test, and we will see how it works ....  
- my first priority is "flexibility" as to how to format/display content on each page (login, logout, registration, reset).  
- Data driven fields is a lower priority here - so hardcoding is OK

**Comment by yasirkhan177** [comment]
ok good .. when i am done .. i will show you
