### ISSUE TITLE
Login Screen (code)

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#5]
Login Screen - internal code/loop ...
please check ... to see that it is not using "subtab"
and please let me know if the "intake" loop (FD fields) is doing anything special  for this page ....
because
after FD Initialization, it takes some extra configuration to get the login screen to work ...  so first I just want to understand how the login screen is being processed, internallly, before specifying any new fixes or enhancements.

**Comment by yasirkhan177** [comment]
in login page .. sub_tab_num = 2 <<< then it will work .. table_alias = login  and  sub_tab_num = 2

**Comment by cjcornell** [comment]
OK - ... 
really - we are not using subtabs yet ... but leave this for now,   because we actually might use subtabs here to create different "areas" for password-reset and for 'register'
