### ISSUE TITLE
Fix Logout Function

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#50]
Logout Function
  - redirects to an invalid page/has bugs
-  should redirect to a special display_page (logout.php?  that actually works correctly) ...  either this logs out - and redirects to the home page - or redirects back to the login page

**Comment by yasirkhan177** [comment]
navigation->item_target = system/logout.php <<< this should be the value

**Comment by cjcornell** [comment]
I get a blank page when I click log out (from the myprojects screen).  Is this a bug or do we need further DD settings?

**Comment by yasirkhan177** [comment]
i just made changes on the index page .. need to change navigation->item_target << value to "system/logout.php" ,lemme change them now
