### ISSUE TITLE
Login - Redirect

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#51]
Login - Redirect
  - (this used to work - needs to work)
  - If user tries to navigate to a page that requires a login - then the system should redirect them to a login/registration page, then after they are logged in successful, redirect the user to the page the originally tried to access

**Comment by yasirkhan177** [comment]
for this i will need a extra field in navigation table. loginCheck or something like this.. is that OK?

**Comment by yasirkhan177** [comment]
you didn't comment on my comment .. """" for this i will need a extra field in navigation table. loginCheck or something like this.. is that OK? """ <<< i want to confirm ,because many times ,you have some other ideas or approach ..

**Comment by cjcornell** [comment]
>> for this i will need a extra field in navigation table. loginCheck or something like this.. is that OK?
Oh - I would rather want to avoid this.  But i get it.
- maybe instead call the field "loginRequired"
- so this means, however, if the user navigates to a display_page with loginRequired=T  AND the user is not already logged in, then
  - GP will direct them to the login (or registration) page ...  how does GP know which page this is?
  - and when the user logs in (or registers) - we want to redirect them back to the original page they requested.

I have a suggestion ... maybe ...
1. we can have a login/registration display_page for "normal" logins ...  (like you are doing in another task)
2. for this case - where the user needs to login because they navigated to a page that requires it ... we have a "popup" form with login form (and links to registration/forgot password).
Understand?

**Comment by yasirkhan177** [comment]
did it without popup form .. it redirects to login page.. check the flow then i will transform it to popup form.

**Comment by cjcornell** [comment]
Looks good for now. if any new issues arise (bugs) - then I will add.  Otherwise enhancements will be added to a newer milestone
