### ISSUE TITLE
Depreciate certain FD/DD fields

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#52]
Depreciate certain FD fields: ensure that the following fields are truly unused and then delete from FD/DD structure and from any internal references:
- FD->sub_tab
- FD->generic_field_order:  display_order should be used  (and display_order's initial values are the generic field order)
- Nulablefield, kefield  - are these  being used anywhere in the code? is it of any use? if not - get rid of

**Comment by yasirkhan177** [comment]
Nulablefield, kefield - are these being used anywhere in the code? is it of any use? if not - get rid of <<<< Nulablefield  <<<<<< didn't get this

**Comment by yasirkhan177** [comment]
check the task

**Comment by cjcornell** [comment]
All you needed to do here, Yasir, is tell me that the fields were indeed not needed (by the current code)  and thus removed.
