### ISSUE TITLE
Extra/Multiple  "select" options  (do this first)

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#53]
#### Extra/Multiple  "select" options  (do this first)
- for all lists (particularly cards and checklists - we are going to extend the functionality so that there is more than one "operation" that can be done on item(s) in the next.  
- For instance: 
  - delete marked items
  - 'close' marked items
  - copy marked items
  - etc
- Or (as you can see in generic very old)
  - Card/Box allows for a click on the image to 'select' and view the project
  - but the "manage" button allows the user to edit the project (if they have privileges)
- So, lists need at least 3 new things
  - a way to specify **what** extra options are available (ie the labels describing the options)
  - a way to specify the function/action associated for each
  - a way to specify how the associated actions are presented to the user (ie:  buttons? icons? links? popup menu? )
- Again this new functionality (if non-blank) will allow for 2 enhancements: either one or the other of:
  - extra 'buttons' or links for  each line (or card) each having different actions, or
  - for multiple checked records in the list, a menu that allows the user to choose an action to be applied to all the checked records.
- note that simply clicking on the record to 'select' should work the way it does now.

**Comment by yasirkhan177** [comment]
So, lists need at least 3 new things
a way to specify what extra options are available (ie the labels describing the options)
a way to specify the function/action associated for each
a way to specify how the associated actions are presented to the user (ie: buttons? icons? links? popup menu? )
Again this new functionality (if non-blank) will allow for 2 enhancements: either one or the other of:
extra 'buttons' or links for each line (or card) each having different actions, or
for multiple checked records in the list, a menu that allows the user to choose an action to be applied to all the checked records.



........................................

if you can little more explain above lines ...

**Comment by cjcornell** [comment]
- lists need at least 3 new things
  - a way to specify what extra options are available (ie the labels describing the options)
  - a way to specify the function/action associated for each
  - a way to specify how the associated actions are presented to the user (ie: buttons? icons? links? popup menu? )

- Again this new functionality (if non-blank) will allow for 2 enhancements: either one or the other of:
  - extra 'buttons' or links for each line (or card) each having different actions, or
  - for multiple checked records in the list, a menu that allows the user to choose an action to be applied to all the checked records.
------------
OK ...
here is a scenario (made-up example):
we specify a that a list is a checklist.  and when the user selects (checks) multiple records ... we want them to have the option to 
"copy, delete, make-private, make-public" 

so - there are at least 3 things needed to be specified in the DD record for the list.
1. what are these options?  (ie the labels for the options: "copy, delete, make-private, make-public")
2. what are the associated functions/actions for each of the options?
3. how does the user see these extra options (right-click? a menu above the list? or perhaps links embedded in the list?

We have to figure out the best way to express this in the DD  (and then implement the funcitonality)

This needs to be discussed and i am open to suggestions.  The most direct way to do this is to add 3 new DD fields   - this is straight-forward but not very efficient.
- multiple_item_options_labels   (comma delimited)
- multiple_item_options_actions   (comma delimited)
- multiple_item_options_appearance  (might work like list_views):  eg
  -  right-click, *buttons, menu

**Comment by yasirkhan177** [comment]
i think this can be achieve by expressing it in one DD field but having flexible protocol.

some rough sketch of the protocol ....

1) label=label-A,action=action-A,appearance=button;label=label-b,action=action-b,appearance=menu;

explanation of above protocol >>>>>> SEMI COLON will separate each action package. WE can further add more enhancement according to our need in this protocol.

**Comment by cjcornell** [comment]
we might not need all the "=" signs
ALSO 
if we make this new field a text field, then we can make it more readable by one "command" per line
ie
item1-label;  item1-action; item-1-link-appearance-style
item2-label;  item2-action; item-2-link-appearance-style
item3-label;  item3-action; item-3-link-appearance-style
item4-label;  item4-action; item-4-link-appearance-style

this might work.
don't forget to save this somewhere as you will have to document it in another milestone later.

**Comment by yasirkhan177** [comment]
here is a scenario (made-up example):
we specify a that a list is a checklist. and when the user selects (checks) multiple records ... we want them to have the option to 
"copy, delete, make-private, make-public" <<<< such things can be achieved without having checklist field in list table. making checklist field is not a big deal for me . discussing here might take much time than making a checklist field in each table of GPC. But ,i'm investing my time for better approach and solution. and let me know the scope of this particular task.

**Comment by cjcornell** [comment]
well, yes, I am open to other approaches.  But I have concerns about
1. memory ... 
if the approach you are thinking requires reading the entire table into memory - then this is trouble
2. future use.
actually I was advocating the checkmark field in all tables for potential future use - where records might be continued to be marked beyond the current session
BUT this was just an idea for future use....
it is not important.

so ... IF you have a better way of achieving this, then, OK.
As long as the user can checkmark records while paging or scrolling  (ie ... mark a lot of different records, not just those on the same page.

Note - I am not sure if it was explcitly spec'd but it makes sense to have an active checkbox in the column-header .. where someone can check-all or uncheck-all  (or another way to do this).
Gmail is a good example of using checkmarks for large lists and applying multiple actions to the checked records.

**Comment by yasirkhan177** [comment]
let me know the scope of this particular task ?? have asked before.. what you want to cover in this task .

**Comment by cjcornell** [comment]
Just what exactly are you not understanding at this point.?  I have
explained this several times.
Exactly what is unclear?
(Note ... if your answer is "everything" then i am going to merely cancel
the milestone)

**Comment by yasirkhan177** [comment]
i think you didn't get me. by scope i meant that for every action there might be a separate function. like for copy ,delete ,etc ... so in this task how many functions you want.

**Comment by cjcornell** [comment]
Please scroll up and RE-read ....

> if we make this new field a text field, then we can make it more readable by one "command" per  line
> ie
> item1-label; item1-action; item-1-link-appearance-style
> item2-label; item2-action; item-2-link-appearance-style
> item3-label; item3-action; item-3-link-appearance-style
> item4-label; item4-action; item-4-link-appearance-style

theoretically this means unlimited options (but limited by how badly it will look in GUI)
no hardcoded limit
OK?

**Comment by yasirkhan177** [comment]
i think we are not getting each other... by this new field .. we can tell the system which action should be there for list, where it should appear and what will be its label. But i need to code functions for each action .. i'm doing one .. i will show you practically then

**Comment by cjcornell** [comment]
I am not sure of your question here....  nor am can i understand where you are unclear.

**Comment by yasirkhan177** [comment]
i will try to explain it via example ...following is the protocol....
item1-label; item1-action; item-1-link-appearance-style
item2-label; item2-action; item-2-link-appearance-style


.................................

let say we want GPC to copy or delete selected lists rows via checkboxes like we do in gmail for deletion 


...........................

1)item1-Delete,item1-delete,item1-top

2)item2-Copy,item1-copy,item1-top


statement-1 means ... when user click on label Delete( whether its link ,icon or button ) ... it will delete all selected records ...

statement-2 means .. when user click on label Copy .. it will copy all selected records....


above actions are data driven .. but GPC will need to have delete and copy function which will be call when user click on link, or button ... 


so right now i'm coding for deletion .. just give me chance to complete it .. you will check it and you will get better idea ..

**Comment by yasirkhan177** [comment]
here by style i will assume CSS STYLE .. in next step we can further modified it .. i'm trying to code it as flexible as possible.. that's why investigating a lot. even though it costing me much time

**Comment by yasirkhan177** [comment]
i will write the whole detail here .....

FIRST OF ALL .. FORGET ABOUT GUI FOR THE MOMENT ( i will work on GUI means styling now )

.................................................

Just check whether GPC working like the way you want only .. i will make it to look like the way you want later. 

.............................................................................

1) Protocols are changed .... i will explain them here ....

you can check dict_id=112 .... i put data there ... 

..... following is the protocol.......

checklist;

delete,Delete But,btn-danger;

copy,copy,copy-class;

........................Explanation is as follow ......................

 every sentence will end with semi colon ( ; ) .. 

1) checklist; <<< it tells the GPC to include checklist to the single line list. ( i didn't did yet for multiline list there were few problems.. i will try later to do it )

2) delete,Delete But,btn-danger; <<< here are there parameters .. 

a) delete<<< tell the GPC to include delete functionality ,which will appear on top of the list in button form ( i will make icons or will see how they look good )

b) Delete << it is the label of button 

c) btn-danger <<< it is the class use particular for that delete button .


............................................

3) copy,copy,copy-class; <<< same like delete ... first parameter will tell gpc to include copying functionality  to the list ...2nd parameter is label for that button and 3rd is class ... but i didn't yet code this .. 


so in this way we can code as many functions as we want .. and can call them via above mention protocol ... 

...................

about """" Checklist """" <<< in future if you want GPC to show link or button infront of each record .. whether its cards or single line list .. by removing checklist ... extra button or link will appear infront of each record and can perform same copy ,delete etc actions ... this functionality is not coded yet .. but i'm just explaining the flexibility of this protocol. Even we can have both option .. like delete button infront of each record and also checklist .. 

...........................................

**Comment by cjcornell** [comment]
OK - Lots for me to mentally process here ... so comment, clarify or correct me below:
- in your description of the parameters ... if seems as if you neglected to describe what the 3rd parameter was for  ("But")
  > 2) delete,Delete But,btn-danger; <<< here are there parameters ..

- I am not clear on one thing ...  the location of the buttons/options
   - ideally we should have 3 kinds of "locations" for us to specify how the user invokes/reveals options for multiple checked items
      - on top of the list
      - inline (extra buttons/icons in to the left or right of the fields in each record)
      - right click - popup menu

**Comment by yasirkhan177** [comment]
i didn't did code for location .. 3rd parameter is to include class.. you can use separate class and call using 3rd parameter .. 

on top of the list
inline (extra buttons/icons in to the left or right of the fields in each record)
right click - popup menu

ideally above 3 mention options are available for users.. on top of the list is done .... what else options you want to cover in this milestone... ???

**Comment by cjcornell** [comment]
I know you did not code for location (which implies right now that the location of the extra options is hard-coded.... and of course I don't want that).

The above is all for this milestone.
checklists is probably the hardest milestone there is  (images might be hard).  After this -everything is is relatively extremely easy.

**Comment by yasirkhan177** [comment]
Sir, i asked because you allocated 60$ for list milestone . so i work according to it. and i try to cover those things which can cover in such price .. that's why i didn't coded location , and i coded style ,which is also needed, whether in this or in future. any how i will code this for now ..

**Comment by cjcornell** [comment]
Actually - List improvements are $60 + $50 bonus.

**Comment by yasirkhan177** [comment]
have uploaded the new build.. links and popup menu feature has been added .. details are as follow.. after posting here .. i will upload spreadsheet .. 

checklist;

popupmenu;

delete,Delete But,btn-danger;

copy,copy,copy-class;

single_delete,left,del-class;

popup_delete,Delete Check,popup-class;

popup_copy,Copy,popup-copy;


few features of above protocol has been already explained. 

popupmenu; <<< it's same like checklist; ... popupmenu tell the system to include popup feature .. 

popup_delete,Delete Check,popup-class; <<< first is action .. popup_delete << it calls a function... 2nd parameter is label of the link ... and third parameter is the styling class

left popup menu option for cards and multi line list as well .. 
.................

single_delete,left,del-class; <<<< it tells GPC to add single row deletion option .. it add icon (which can be change later ) .. first parameter tells GPC to add single delete option.. 2nd parameter tells GPC to display the icon side .. whether its left or right side of the page .. 3rd parameter is style class ..

normally icons are on left side of the list .. so if you right above protocol like this >>> single_delete,del-class;  <<< still it will display icon on left side of the page ..

**Comment by cjcornell** [comment]
Excellent.
I am going to close out the milestone and all the tasks now ... But
1. Please document very well, as part of the 'documentation" milestone
   - consider using the Gitbub wiki front end ...
2. I am going to test and configure over the next few weeks. - No doubt I will find some bugs ..
3. critical bugs (that prevent functionality), I expect to log and have fixed
4. Other bugs or enhancements I will log for a future milestone.
Thanks!
Good work.

**Comment by yasirkhan177** [comment]
pleasures.. i will try to document in good possible way (though don't have much experience).. i will do documentation later.... 

i'm always here,whenever you call on me .. 

Thanks,

**Comment by cjcornell** [comment]
re: documentation ...
don't focus too much on style or formatting ...
just focus on clarity of the information, and organization.

**Comment by yasirkhan177** [comment]
ok..
