### ISSUE TITLE
Checklists

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#55]
Checklists
+  Need an internal DD flag that denotes a child/Crossref table as a checklist. (perhaps the word "Check" at he end of the list_style?  ListCheck  ) - already spec'd.
+ All Tables should have a special checkmark field future functionality of lists with checkmarks. 
+ Need a way for the DD_Init system to automatically add this field (to the structure of each table) if it does not exist in each table. 
+ Special format_type checkmark
+ operationally ... if this is a checklist, then 
  - every "line" (record) in the list has a checkbox next to it
  - user can click the checkbox (or one or more) when selecting multiple records
  - if no individual records are checked, then a single record can be selected and list_select is executed as usual
  - if one or more records are checked, then a different list select directive (function) is executed
 - ?? perhaps the multiselect function is specified in the second parameter of a comma delimted list_select field.
  - user can quickly select all, or none (uber-checkbox) ... or select "some" using control click
  - all selections are cleared upon initial display of the list
Also See Github Issue #57   (for multiple selection options)

**Comment by yasirkhan177** [comment]
i didn't get an idea why you want checklist field in each table? what you describe and what you want to achieve from checklist .. i think this can be achieve from #53 ????

**Comment by cjcornell** [comment]
If you are implementing checklists as per my suggestion, then the table (that is being used for the list) needs an extra field to indicate which records are checked.
Thus, any table that might ever be used as a checklist will need this extra field.

**Comment by yasirkhan177** [comment]
my point is .. if records are checked in the table which is used for list .. what gpc will do with those checked records? 

i mean if we want to delete ,copying multiple records from list .. we don't need checklist field ?

**Comment by cjcornell** [comment]
One of us is not understanding the other.
if a list (table) has 1,000 records, how are you keeping track of which
ones are checked (marked) for any kind of multiple-action?

**Comment by yasirkhan177** [comment]
well, if you want to run some functionality at the backend(in background) like cronjobs .. then this can be an option.. but if you want to have multiple action on selected rows on the same page regarding of how many records are selected or not .. then this can be achieve via jquery .. and if you want a scenario where javascript is disable then it can be an exception. but now a days mostly admins asked users to enable javascript to have extra functionality or for your ease

**Comment by yasirkhan177** [comment]
i will suggest .. lets go like this .. if we feel that there is checklist needed .. then it will be dealt. i will keep this in my mind .. it wont take me to do changes a lot to accomplish.

**Comment by cjcornell** [comment]
Ok. This is good.

**Comment by yasirkhan177** [comment]
checkbox option will be available only for simple lists? which is listView in GPC case?? wanna confirm it.. and if it is available for only for single line list then would user have option to toggle between list listviews .. which is boxview(cards) and multiline list (xList) ...

**Comment by cjcornell** [comment]
well I had no expectations for checklists for boxes - but maybe for multilined lists if this is not too code-disruptive (not sure there should be a big difference.

if the user toggles between list types 
- of course no checkmarks would appear on lists/boxes that are not "checklists"
- but ideally the checkmarks (and options) would be preserved, if they toggled back to the checklist
- of course this only applies during a list "session" - if they leave the list and return, then checkmarks are cleared.

**Comment by yasirkhan177** [comment]
will be like this ,how you stated in your recent most comment
