### ISSUE TITLE
Lists - No labels

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#56]
Labels should not appear in and list format right now ...
(we will later specify how labels will be displayed - in column headings, in another milestone.

**Comment by cjcornell** [comment]
bump.  note this only applies the List (xlist etc) ... not the box/card formats

**Comment by yasirkhan177** [comment]
fixed now .. with which i don't add "fix applied test" label.. its mean i didn't fix this

**Comment by cjcornell** [comment]
OK- before I close this - I saw that when "list-style"  class was applied to one of the lists - the labels appeared before the fields?  Is this correct?  that you were able to remove or add field labels via css?
