### ISSUE TITLE
Initial Login Screen - Erroneous Warnings

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#64]
The initial login screen (http://generic.cjcornell.com/system/login.php)
has 

Login required to view the current page!
Login required to view the current page!
Login required to view the current page!
Login required to view the current page!
Login required to view the current page!
Login required to view the current page!
Login required to view the current page!
Login required to view the current page!

While this might be a temporarily thing while testing, I still want to log it so we know it needs to be fixed.

**Comment by yasirkhan177** [comment]
i mention this on slack .. ( i'm fixing it ) it has nothing to do with code though .

**Comment by cjcornell** [comment]
np.  i just want to log it
