### ISSUE TITLE
List - Border around single line list

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#65]
I reported this before ...  
why is there a border around single-lined lists?
(see myprojects-page->scripts tab  and and myprojects-page->My Projects Tab

I checked to see the default style for Lists  (could not really find it) to see if this was just a style issue.

**Comment by yasirkhan177** [comment]
sorry i didn't see your report regarding to border line. it's styling issue ,it will be dealt

**Comment by cjcornell** [comment]
1. Styling issue (meaning css class?) - good. OK
2. yes, remove borders only from single line lists - so the line items can be closer together and thus more lines per screen
(still need to test multiple pages)
